# Generated by Django 5.0.4 on 2024-05-11 23:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=500)),
                ('data_lancamento', models.DateField(blank=True)),
                ('pub_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating_c', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rating_u', models.DecimalField(decimal_places=1, max_digits=5)),
                ('video_trailler', models.URLField()),
                ('imagem_jogo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagemJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.URLField()),
                ('jogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='site_app.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_c', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rating_u', models.DecimalField(decimal_places=1, max_digits=5)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.jogo')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('pub_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_c', models.IntegerField(default=0)),
                ('like_u', models.IntegerField(default=0)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.jogo')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='site_app.rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.review')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(blank=True)),
                ('empresa', models.CharField(max_length=50)),
                ('numero_reviews', models.IntegerField(default=0)),
                ('is_cristico', models.BooleanField(default=False)),
                ('imageurl', models.URLField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video_trailler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidcurl', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
