# Generated by Django 5.0.4 on 2024-05-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_trailler',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImagemJogo',
        ),
        migrations.DeleteModel(
            name='Video_trailler',
        ),
    ]
